#!/bin/zsh
zmodload -F zsh/stat b:zstat

die () { echo "$(basename $0): $@" >&2; exit 1; }

is_llvm_dir () { [ -d .git ] && [ -d include/llvm ]; }

original_device=$(zstat +device .)
until is_llvm_dir; do
    cd ..
    if [ $PWD = / ] || [ $original_device -ne $(zstat +device .) ]; then
        die "Not in LLVM repository?"
    fi
done

rc=0
echo -n "llvm: ";
git "$@" || : $((rc++))
for repo in */**/.git(/:h); do
    (cd $repo; echo -n "${PWD:t}: "; git "$@") || : $((rc++))
done

exit $rc
